### DISCUSSION TITLE
June 15th, 2021: CloudFormation, SageMaker, EC2, and SES

### DISCUSSION THREAD

**Discussion by jdisanti** [awslabs/aws-sdk-rust#112] [General]
This week, we've added CloudFormation, SageMaker, EC2, and SES. More details below.

To upgrade to the new release, update `tag` to `v0.0.8-alpha`:

```toml
[dependencies]
# eg. EC2:
aws-sdk-ec2 = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.8-alpha" }
```

**New this Week**
- 🎉 Add support for CloudFormation (smithy-rs#500, @alistaim)
- 🎉 Add support for SageMaker (smithy-rs#473, @alistaim)
- 🎉 Add support for EC2 (smithy-rs#495)
- 🎉 Add support for SES (smithy-rs#499)
- Add support for the EC2 Query protocol (smithy-rs#475)
- Refactor smithy/hyper connectors to enable client-specified middleware (smithy-rs#496, @jonhoo)
- 🐛 Bugfix: RFC-3339 timestamp formatting is no longer truncating zeros off of the number of seconds (smithy-rs#479, smithy-rs#489)

Contributors:
- @Doug-AWS
- @jdisanti
- @rcoh
- @alistaim
- @jonhoo

Thanks!!

<hr /><em>This discussion was created from the release <a href='https://github.com/awslabs/aws-sdk-rust/releases/tag/v0.0.8-alpha'>June 15th, 2021: CloudFormation, SageMaker, EC2, and SES</a>.</em>
