### DISCUSSION TITLE
Re-export hyper and aws-smithy-client

### DISCUSSION THREAD

**Discussion by lcmgh** [awslabs/aws-sdk-rust#533] [General]
Relates to [How can I customize the settings on the hyper client used by the SDK? ](https://github.com/awslabs/aws-sdk-rust/discussions/448)

From what I understand one would need to add the following dependencies to work with adapted hyper settings (e.g. proxy)
```TOML
hyper = "0.14.18"
aws-smithy-client = { version = "0.40.2", features = ["client-hyper"] }
```

Does it make sense to re-export `hyper` and `aws-smithy-client` to reduce the overall number of dependencies clients have to add?
