### ISSUE TITLE
Add support for `AWS_ENDPOINT_URL` environment variable

### ISSUE THREAD

**Issue by Walther** [awslabs/aws-sdk-rust#932]
### Describe the bug

`AWS_ENDPOINT_URL` in the environment gets ignored by the SDK.

### Expected Behavior

The correct endpoint URL will be loaded from the environment variables and used for the SDK client(s).

### Current Behavior

The endpoint URL gets ignored, and requests will be made against the AWS production endpoints.

### Reproduction Steps

`main.rs`:

```rust
use anyhow::Result;
use dotenv::dotenv;

#[tokio::main]
async fn main() -> Result<()> {
    // load configs
    dotenv().ok();
    let region = dotenv::var("AWS_DEFAULT_REGION")?;
    println!("{region}");
    let endpoint = dotenv::var("AWS_ENDPOINT_URL")?;
    println!("{endpoint}");

    // load aws config
    let awsconfig = aws_config::load_from_env().await;
    let s3client = aws_sdk_s3::Client::new(&awsconfig);
    println!("{:?}", s3client);

    Ok(())
}
```

`.env`:
```
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test
AWS_DEFAULT_REGION=eu-north-1
AWS_ENDPOINT_URL=http://localstack:4566
AWS_ENDPOINT_URL_S3=http://localstack:4566
ENDPOINT_URL=http://localstack:4566
```

_(Note: I've included a couple of additional possible spellings of the endpoint URL in order to eliminate the possibility of the error originating from a slight naming difference)_

Running this code and searching the output for `EndpointUrl` shows that the endpoint URL has not been configured correctly.

### Possible Solution

Workaround: manually setting the endpoint override works, but this is not ideal:

```rust
use anyhow::Result;
use dotenv::dotenv;

#[tokio::main]
async fn main() -> Result<()> {
    // load configs
    dotenv().ok();
    let region = dotenv::var("AWS_DEFAULT_REGION")?;
    println!("{region}");
    let endpoint = dotenv::var("AWS_ENDPOINT_URL")?;
    println!("{endpoint}");

    // load aws config
    let awsconfig = aws_config::from_env().endpoint_url(endpoint).load().await;
    let s3client = aws_sdk_s3::Client::new(&awsconfig);
    println!("{:?}", s3client);

    Ok(())
}
```

---

I wonder if this error is originating from here: https://github.com/awslabs/aws-sdk-rust/blob/464d7822b7efc5761e66393e87386f65c6deaf4a/sdk/aws-config/src/lib.rs#L670-L677

### Additional Information/Context

Being able to set the endpoint URL would be really useful for local development. Consider for example the following snippet for Docker Compose, utilizing LocalStack:

```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.3
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=s3:4566
      - DEBUG=${DEBUG-}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  createbucket:
    image: amazon/aws-cli:2.13.29
    depends_on:
      - localstack
    volumes:
      - bucket:/aws
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-north-1
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket testbucket --region eu-north-1 --create-bucket-configuration LocationConstraint=eu-north-1
      "

  # other services, including the client that uses the Rust SDK

volumes:
  bucket:
```

and the client container having a `.env` file with the appropriate `AWS_ENDPOINT_URL` and other env vars.

### Version

```text
aws-config = "0.56.1"
aws-sdk-s3 = "0.34.0"
```

### Environment details (OS name and version, etc.)

macOS Sonoma 14.0
